# Generated by Django 4.2.6 on 2023-12-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(max_length=300, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_numer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
