# Generated by Django 4.2.6 on 2023-12-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_acc',
            field=models.IntegerField(null=True),
        ),
    ]
